### ISSUE TITLE
FCC HTML

### ISSUE THREAD

**Issue by blitz137** [blitz137/learn#3]
Start the Responsive Web Design Certification on the site.

**Comment by blitz137** [comment]
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5

**Comment by leigh18** [comment]
![image](https://user-images.githubusercontent.com/53063405/62251994-17ba8e80-b3b7-11e9-9532-23ba0fcf7929.png)

**Comment by blitz137** [comment]
Good job Lily!

**Comment by leigh18** [comment]
![image](https://user-images.githubusercontent.com/53063405/63120716-73b11580-bf68-11e9-9eea-633887f2bd96.png)

**Comment by leigh18** [comment]
i finished the css thing

**Comment by leigh18** [comment]
you want me to start Applied Visual Design?

**Comment by blitz137** [comment]
Yes do that. Have you done scrimba yet? Move the conversation over to issue #5
